### ISSUE TITLE
Hyperlinks to terms

### ISSUE THREAD

**Issue by k-toumura** [w3c/wot-architecture#85] opened 2019-02-20 06:10 UTC
[Editorial]
In a past teleconference or F2F, there was a discussion about a style of hyperlinks to terminology section.
For example, in [Building Blocks](https://w3c.github.io/wot-architecture/#building-blocks), [Servient Implementation](https://w3c.github.io/wot-architecture/#servient-implementation) and [Security and Privacy Considerations](https://w3c.github.io/wot-architecture/#sec-security-considerations), terms are repeatedly linked to terminology section.  On the other hand, other sections have no links to terminology.

Which style is preferred in this document?

1.   Make all occurrence of technical term be linked to terminology section to clarify their meaning.
2.  Link only from first occurrence of the term for the conciseness.

And, there are lots (55) of broken reference to terminology section.  If needed (especially when we choose an option 1 above),  I'll make a pull request to fix them.   
![screen shot 2019-02-20 at 15 42 36](https://user-images.githubusercontent.com/30313213/53071685-412cdf80-3526-11e9-8592-2606738373dd.png)

**Comment by k-toumura** [comment] 2019-02-21 09:51
Option 3 (in Feb 20 teleconference)
3. Make all occurrence of technical term be linked to terminology section, but use plain style for these links.  (by @takuki)

For example, [JSON-LD 1.0](https://www.w3.org/TR/json-ld/) uses following style for links to terminology section:
```css
a.internalDFN[data-link-type="dfn"] {
    color: inherit;
    border-bottom: 1px solid #99c;
    text-decoration: none;
}
```

**Comment by takuki** [comment] 2019-02-21 14:21
@k-toumura, JSON-LD 1.0's way to link to definitions appears very useful and yet non-obtrusive, which I think is exactly what we want in our document as well.

**Comment by mkovatsc** [comment] 2019-02-25 13:10
+1 for keeping all links but using a more moderate CSS class.

**Comment by mlagally** [comment] 2019-02-26 16:50
@k-toumura This looks good, can you please create a PR?

**Comment by mlagally** [comment] 2019-02-27 14:24
PR: https://github.com/w3c/wot-architecture/pull/89

**Comment by mlagally** [comment] 2019-03-07 15:28
Pr was merged - the issue is resolved.

**Closed by mlagally** 2019-03-07 15:28 UTC
Labels: PR available, review
